---
title: "Alexander Looi Bio:"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

[Home](https://looixiv.github.io/Wedding.html)

Alexander Looi (Alex on the East Coast, Looi on the West Coast) is the son of Mark Looi and Susan Cheng-Looi. He grew up in Issaquah Washington (an eastern suburb of Seattle, famous for the band Modest Mouse!) with his brother Terence Looi. There he spent middle and high school running the damp trails of the Cascade Mountain Range.

Alex did pick up playing the guitar during his senior year of high school but was not good enough to form a hit alternative rock band so he settled for earning a B.S. in Natural Resources concentrating on Applied Ecology from Cornell University. To prepare for graduate school he took a gap year and worked in a lab on Cornell's campus after graduating. During that gap year he met Julie Quinn, whose sense of humor, quirkiness, athletic ability, and intelligence enthralled him. They started formally dating after several pseudo-dates.

After Alex's gap year over the next 6-7 years he pursued two masters degrees, one from SUNY-ESF in watershed and eco-system modeling, the other from the University of Vermont in Complex Systems and Data Science, and worked for the USGS as an ecological modeller. During that time they maintained a long distance relationship where they frequently kept silent company through FaceTime/Skype sessions as they worked on their respective degrees. 

In 2017 Alex proposed to Julie at the finish line of the Philadelphia Marathon, where she qualified for the 2020 Olympic Trials. They live together now in Charlottesville, Virginia. There Alex works at Commonwealth Computing Research Inc. as a machine learning data scientist. Julie is now an assistant professor at the University of Virginia working on optimizing the conflicting objectives of stake holders at the Water Energy Nexus using Latin Hyper Cubes, Pareto Fronts, and Borg.