---
title: "Other Places to Visit in and Around Ithaca"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---
[Home](https://looixiv.github.io/Wedding.html)

## State Parks
### Less than 10 min outside Down town Ithaca
[Buttermilk Falls](https://parks.ny.gov/parks/151/details.aspx)
[Taughannock falls](https://parks.ny.gov/parks/62/details.aspx)  
[Treman State Park](https://parks.ny.gov/parks/135/details.aspx)  
[Stewart Park](https://www.cityofithaca.org/516/Stewart-Park)

## Cornell's Campus

[Cornell Botanic Gardens](https://cornellbotanicgardens.org/)

[Cornell Brain Collection!](https://ithacating.com/2014/12/27/the-brains-of-uris-hall/)

[Cornell Campus Tours](https://www.cornell.edu/visit/#tours) 

## Wineries
There are many wineries in and around Cayuga Lake. Below is a link to the Cayuga Lake Wine Trail, a list of some of the most popular wineries along Cayuga Lake!

[Cayuga Lake Wineries](https://www.cayugawinetrail.com/wineries/)

There are other wineries in the area, and other lakes! Feel free to explore the area! One of the most "interesting/bizzare" wineries is [Rasta Winery](http://www.fingerlakeswinecountry.com/listings/rasta-ranch-vineyards/663/). You go there not for the wine, but more for the quirky atmosphere!

## Other Towns

Another Ithaca like town in to the west is [Watkins Glen](https://www.watkinsglenchamber.com/) on neighboring Seneca Lake. There is another wonderful called [State Park (Watkins Glen State Park)](https://parks.ny.gov/parks/142/).

Fifteen minutes east of Ithaca is Dryden which has [go kart racing](http://www.ringwoodracewaygokarttrack.com/)!

An hour north of Ithaca is Syracuse home to the Orange Men. But more tastily, the famous [Dinosaur BBQ](https://www.dinosaurbarbque.com/).

[Home](https://looixiv.github.io/Wedding.html)