---
title: "Places to Book Your Stay in Ithaca"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---
The wedding will be 4:30 pm at the Statler Ballroom on July 27th.

Unfortunately Statler Hotel is full and we could only reserve a couple rooms for us and our family. Here's a list of a few other nice hotels in the area:  

### A Google Map Link to a Map of Hotels in the Area
Here is a map of available hotels in the area. Note that the listed prices are for the wedding weekend. The initial dates set are for July 27 to the 28th. If you would like to stay longer just use the sliding bars to adjust the date range, or manually enter in your desired date range.  


[Map here](https://www.google.com/travel/hotels/Ithaca?ap=SAEqVAoSCaK2UG9fMkVAETillNfxJFPAEhIJGiTo4EhARUAR4Ka5s-waU8AaKgobEQwmp0XvH1PAGV5tHChUOUVACYlum4UesulAGgYIkAcQ2gYlmplRQTABWqABCgUIrAIQACIDVVNEKhYKBwjjDxAHGBkSBwjjDxAHGBwYAyABigFUChIJorZQb18yRUAROKWU1_EkU8ASEgkaJOjgSEBFQBHgprmz7BpTwBoqChsRDCanRe8fU8AZXm0cKFQ5RUAJiW6bhR6y6UAaBgiQBxDaBiWamVFBmgEIEgZJdGhhY2GiARIKCC9tLzAzdl81EgZJdGhhY2GSAQIgAQ&g2lb=4181926%2C4208993%2C4209588%2C4223281%2C4225904%2C4207631%2C4220469%2C4226108%2C4226112&hl=en&gl=us&un=0&q=hotel%20ithaca&rp=OAFAAA&ictx=1&sa=X&ved=0ahUKEwi1x_OomOLfAhXiSt8KHUpuC0IQtgMIfA&hrf=CgUIrAIQACIDVVNEKhYKBwjjDxAHGBsSBwjjDxAHGBwYASABigFUChIJorZQb18yRUAROKWU1_EkU8ASEgkaJOjgSEBFQBHgprmz7BpTwBoqChsRDCanRe8fU8AZXm0cKFQ5RUAJiW6bhR6y6UAaBgiQBxDaBiWamVFBmgEIEgZJdGhhY2GiARIKCC9tLzAzdl81EgZJdGhhY2GSAQIgAQ&tcfs=EiwKCC9tLzAzdl81EgZJdGhhY2EaGAoKMjAxOS0wNy0yNxIKMjAxOS0wNy0yOCIYCgoyMDE5LTA3LTI3EgoyMDE5LTA3LTI4UgA)  

### An AirBnB Map to Rentable Rooms in the Area
Here is a map of some available rentable rooms int he rea. Note that the listed prices are for the wedding weekend (27th to the 28) for two adults.  


[Map Here](https://www.airbnb.com/s/Ithaca--NY--United-States/homes?refinement_paths%5B%5D=%2Fhomes&checkin=2019-07-27&adults=2&children=0&infants=0&place_id=ChIJ94iv4IKB0IkRdM5upWgn5Qo&query=Ithaca%2C%20NY%2C%20United%20States&click_referer=t%3ASEE_ALL%7Csid%3Ac3219e46-7399-496b-aedc-945fa8d8c5cb%7Cst%3ALANDING_PAGE_MARQUEE&allow_override%5B%5D=&checkout=2019-07-28&s_tag=RaLETA6n)  


### Downtown (<10 min):  
Ithaca Marriott Downtown ([booking](https://www.reservations.com/hotel/ithaca-marriott-downtown-on-the-commons-ithaca-ny?rmcid=dsa&gclid=EAIaIQobChMIjKL_h9fX3wIVhB-GCh0SDwdyEAAYAiAAEgLW__D_BwE); [directions](https://www.google.com/maps/dir/Ithaca+Marriott+Downtown+on+the+Commons,+120+S+Aurora+St,+Ithaca,+NY+14850/Statler+Dr,+Ithaca,+NY+14853/@42.4418673,-76.4903548,16z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x89d0819b9e61d8c5:0x491c811d04871d56!2m2!1d-76.495525!2d42.438972!1m5!1m1!1s0x89d0818b734b4fbf:0x19e517804b10dd40!2m2!1d-76.4815864!2d42.4458011!3e0))

Hilton Garden Inn Ithaca ([booking](http://www.guestreservations.com/hilton-garden-inn-ithaca/booking?gclid=EAIaIQobChMI6fTd49bX3wIVjbbICh25pQlJEAAYAiAAEgJvRPD_BwE); [directions](https://www.google.com/maps/dir/Hilton+Garden+Inn+Ithaca,+East+Seneca+Street,+Ithaca,+NY/Statler+Dr,+Ithaca,+NY+14853/@42.4438289,-76.4991278,15z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x89d0819c97f6b33f:0x698a65e058656089!2m2!1d-76.4973132!2d42.4407115!1m5!1m1!1s0x89d0818b734b4fbf:0x19e517804b10dd40!2m2!1d-76.4815864!2d42.4458011!3e0))

Hotel Ithaca ([booking](http://www.guestreservations.com/hotel-ithaca/booking?gclid=EAIaIQobChMIpOz-0tfX3wIVRksNCh24rAlfEAAYASAAEgKT7vD_BwE); [directions](https://www.google.com/maps/dir/The+Hotel+Ithaca,+222+S+Cayuga+St,+Ithaca,+NY+14850/Statler+Dr,+Ithaca,+NY+14853/@42.4416546,-76.5051786,14z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x89d0819c3470b25f:0x19658260249e7c93!2m2!1d-76.4991141!2d42.4375998!1m5!1m1!1s0x89d0818b734b4fbf:0x19e517804b10dd40!2m2!1d-76.4815864!2d42.4458011!3e0))

### Further downtown (10-15 min):  
Hampton Inn ([booking](http://www.guestreservations.com/hampton-inn-ithaca/booking?gclid=EAIaIQobChMI4rrZjNjX3wIVw2SGCh0SEwhAEAAYAiAAEgIonfD_BwE); [directions](https://www.google.com/maps/dir/Hampton+Inn+Ithaca,+Elmira+Road,+Ithaca,+NY/Statler+Dr,+Ithaca,+NY+14853/@42.4356499,-76.5123588,14z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x89d0810fefda4879:0x78ba86e30740a0c5!2m2!1d-76.5132424!2d42.4248629!1m5!1m1!1s0x89d0818b734b4fbf:0x19e517804b10dd40!2m2!1d-76.4815864!2d42.4458011!3e0))  

Holiday Inn Express & Suites Ithaca ([booking](https://www.ihg.com/holidayinnexpress/hotels/us/en/ithaca/ithex/hoteldetail?qDest=Ithaca,%19NY,%20United%20States&qCiD=5&qCoD=6&qCiMy=02019&qCoMy=02019&qAdlt=1&qChld=0&qRms=1&qWch=0&qSmP=1&qIta=99504425&glat=SEAR&setPMCookies=true&qRtP=6CBARC&qAkamaiCC=US&srb_u=1&qRad=30&qRdU=mi&presentationViewType=null&qBrs=re.ic.in.vn.cp.vx.hi.ex.rs.cv.sb.cw.ma.ul.ki.va); [directions](https://www.google.com/maps/dir/Holiday+Inn+Express+%26+Suites+Ithaca,+371+Elmira+Rd,+Ithaca,+NY+14850/The+Statler+Hotel,+Statler+Drive,+Ithaca,+NY/@42.4366849,-76.5176133,14z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x89d0811b9885e527:0x25065a416a320391!2m2!1d-76.5176399!2d42.4212134!1m5!1m1!1s0x89d0818b0848a40f:0x14dd1f9150f89ebd!2m2!1d-76.48231!2d42.446388!3e0))  

### By the mall (10-15 min):  
Homewood Suites by Hilton Ithaca ([booking](http://www.guestreservations.com/homewood-suites-by-hilton-ithaca/booking?gclid=EAIaIQobChMI3Kj_p9jX3wIVyh6GCh0hnw3MEAAYAiAAEgK79vD_BwE); [directions](https://www.google.com/maps/dir/Homewood+Suites+by+Hilton+Ithaca,+Cinema+Drive,+Ithaca,+NY/Statler+Dr,+Ithaca,+NY+14853/@42.4621902,-76.4900091,14z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x89d082677b8b620b:0x382984b24cb776d2!2m2!1d-76.4792714!2d42.4804354!1m5!1m1!1s0x89d0818b734b4fbf:0x19e517804b10dd40!2m2!1d-76.4815864!2d42.4458011!3e0))  

### By the airport (10-15 min):  
Courtyard by Marriot Ithaca ([booking](https://www.reservations.com/hotel/courtyard-by-marriott-ithaca-lansing?rmcid=dsa&gclid=EAIaIQobChMI6fby3djX3wIVAVuGCh3hhQRAEAAYAiAAEgJw5_D_BwE); [directions](https://www.google.com/maps/dir/Courtyard+by+Marriott+Ithaca+Airport%2FUniversity,+29+Thornwood+Dr,+Ithaca,+NY+14850/Statler+Dr,+Ithaca,+NY+14853/@42.4651982,-76.4803918,13z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x89d0827e6a873b99:0x89578d38567d9039!2m2!1d-76.4652659!2d42.4833222!1m5!1m1!1s0x89d0818b734b4fbf:0x19e517804b10dd40!2m2!1d-76.4815864!2d42.4458011!3e0))

### Non-Hotel option
[AirBnB](https://www.airbnb.com/a/?af=43720035&c=.pi0.pk25650614176_233093750306_c_12026460346&sem_position=1t1&sem_target=aud-428713872427:kwd-12026460346&location_of_interest=&location_physical=9008356&ghost=true&gclid=Cj0KCQiA68bhBRCKARIsABYUGifdcqVpnq1x6DxQWtenkC2irWNERLy18-LV9wllyRkMss5pJkyUVX4aAg16EALw_wcB)


